import { Toaster } from "react-hot-toast"
import "./globals.css"
import { Inter } from "next/font/google"
// import dynamic from "next/dynamic"

// const NoSsrAuthGuard = dynamic(() => import("@/components/Auth/AuthGuard"), { ssr: false })
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NoSsrAuthGuard > */}
        {children}
        {/* </NoSsrAuthGuard> */}
        {/* {children} */}
        <div id="modal"></div>
        <div id="modal-loader"></div>
        <Toaster/>
      </body>
    </html>
  )
}
